#!/bin/bash

# UUID of the internal monitor
internal_monitor_uuid="37D8832A-2D66-02CA-B9F7-8F30A301B230"

# Get the list of all connected monitors
monitors=$(yabai -m query --displays)

# Loop through each monitor and apply settings if it is not the internal monitor
echo "$monitors" | jq -c '.[]' | while read -r monitor; do
  # Extract the monitor's UUID
  uuid=$(echo "$monitor" | jq -r '.uuid')

  # Check if the monitor's UUID is not the internal monitor's UUID
  if [ "$uuid" != "$internal_monitor_uuid" ]; then
    # Extract the monitor's id
    id=$(echo "$monitor" | jq '.index')

    # Apply your configurations to the external monitor
    yabai -m config layout bsp
    yabai -m config top_padding 4
    yabai -m config right_padding 4
    yabai -m config bottom_padding 4
    yabai -m config left_padding 4
    yabai -m config window_gap 4
    yabai -m config mouse_follow_focus true
    yabai -m config mouse_drop_action stack
  fi
done
